#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#Find the sum of all the even-valued terms in the sequence which do not exceed four million.
  
require File.join(File.dirname(__FILE__),'../../../lib/fibonacci.rb')

sum_of_even_values = 0
f = Fibonacci.new

f.each do |num|
  if num > 4000000
    f.done
  else
    if num % 2 == 0
      #puts "Adding #{num} to sum"
      sum_of_even_values += num
    end
  end
end

puts "Sum of all even valued terms of the fibonacci sequence which do not exceed four million"
puts sum_of_even_values
